# Tensorflow

In [ ]:
import tensorflow as tf

x_tf = tf.constant([1.0,0.5])
print(x_tf)
# shape=(2,) means 1 DIMENSION holding 2 values — NOT 2 columns.
# There is no second dimension here at all; this is a flat vector,
# not a row or column vector (those only exist once you're 2D:
# [[1.0, 0.5]] = 1x2 row vector, [[1.0],[0.5]] = 2x1 column vector)


w_tf = tf.constant([[1,2,3],[4,5,6]]) # shape(2, 3)
print(w_tf.shape)
# double brackets = nested lists = 2 dimensions. Outer list = rows,
# each inner list = one row's values. shape=(2,3): 2 rows, 3 columns —
# same rows-by-columns idea as df.shape, but tensors aren't locked to
# 2D the way a DataFrame always is

# element-wise ops: matching POSITIONS combine
a_tf = tf.constant([1.0, 2.0, 3.0])
b_tf = tf.constant([4.0, 5.0, 6.0])
print(a_tf + b_tf)
print(a_tf * b_tf)

# Matrix multiplication
v_tf = tf.constant([[1, 0], [0, 1], [1, 1]])  # shape (3, 2)
print(tf.matmul(w_tf, v_tf))
# THIS is the real mechanism behind a neuron's weighted sum:
# X (1xN row vector of inputs) matmul W (NxM matrix of weights,
# one COLUMN per neuron) = one raw z per neuron, computed all at
# once instead of looping w1*x1+w2*x2+... for each neuron separately

tf.Tensor([1.  0.5], shape=(2,), dtype=float32)
(2, 3)
tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
tf.Tensor(
[[ 4  5]
 [10 11]], shape=(2, 2), dtype=int32)


# Pytorch

In [ ]:
import torch 

x_torch = torch.tensor([1.0, 0.5])
print(x_torch)

w_torch = torch.tensor([[1,2,3],[4,5,6]]) # shape (2, 3)
print(w_torch.shape)

# element-wise ops: matching POSITIONS combine
a_torch = torch.tensor([1.0, 2.0, 3.0])
b_torch = torch.tensor([4.0, 5.0, 6.0])
print(a_torch + b_torch)
print(a_torch * b_torch)

# Matrix multiplication
v_torch = torch.tensor([[1, 0], [0, 1], [1, 1]])  # shape (3, 2)
print(torch.matmul(w_torch, v_torch))


tensor([1.0000, 0.5000])
torch.Size([2, 3])
tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([[ 4,  5],
        [10, 11]])
